package com.comye1.catcat.catbreed.models

data class BreedItem(
    val adaptability: Int = -1,
    val affection_level: Int = -1,
    val alt_names: String = "",
    val bidability: Int = -1,
    val cat_friendly: Int = -1,
    val cfa_url: String = "",
    val child_friendly: Int = -1,
    val country_code: String = "",
    val country_codes: String = "",
    val description: String = "",
    val dog_friendly: Int = -1,
    val energy_level: Int = -1,
    val experimental: Int = -1,
    val grooming: Int = -1,
    val hairless: Int = -1,
    val health_issues: Int = -1,
    val hypoallergenic: Int = -1,
    val id: String = "",
    val image: Image?,
    val indoor: Int = -1,
    val intelligence: Int = -1,
    val lap: Int = -1,
    val life_span: String = "",
    val name: String = "",
    val natural: Int = -1,
    val origin: String = "",
    val rare: Int = -1,
    val reference_image_id: String = "",
    val rex: Int = -1,
    val shedding_level: Int = -1,
    val short_legs: Int = -1,
    val social_needs: Int = -1,
    val stranger_friendly: Int = -1,
    val suppressed_tail: Int = -1,
    val temperament: String = "",
    val vcahospitals_url: String = "",
    val vetstreet_url: String = "",
    val vocalisation: Int = -1,
    val weight: Weight,
    val wikipedia_url: String = ""
)